### ISSUE TITLE
Add metrics which leverage registration data

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_cloudmetrics#132]
- [ ] this needs to work even if the site isn't registered
 Add these metrics: (these should be all 'registration' ones but if some aren't lets split those into other issues)

* [ ] Number of users (138371)
* [ ] Number of recently active users (18095)
* [ ] Number of role assignments (971597)
* [ ] Number of posts (392798)
* [ ] Number of questions (7099796)
* [ ] Number of resources (214837)

**Comment by jaypha** [comment]
Any suggested colours?

**Comment by brendanheywood** [comment]
Ah! sorry we already have this data, I'm cancelling this one sorry
