### ISSUE TITLE
Improve on the 1000 record limit and automatically reduce the resolution if you zoom out

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_cloudmetrics#148]
Lets say you are looking at 1 days worth of data in 5 minute increments, and then zoom out to a week or a month. If you would hit the 1000 record limit then automatically change the increment from 5 minutes up a notch until you are under the 1000 record limit.

I'm on the fence around whether this is an internal safeguard or whether it would change the parameters for you.

**Comment by jaypha** [comment]
I don't think it should change any parameters. It should bounce back if it ever goes under 1000 again.

It may be a good idea to give a notice when this is being done.

**Comment by brendanheywood** [comment]
+1 I like the elastic idea too
