### ISSUE TITLE
Plugins db approval blocker: Plugins db description a bit too light.

### ISSUE THREAD

**Issue by danmarsden** [catalyst/moodle-tool_cloudmetrics#162]
The description added to the plugins db is pretty light on detail on what this plugin is actually for and why a Moodle site would use it... can it be improved a bit?

**Comment by bwalkerl** [comment]
Has been updated.

**Comment by danmarsden** [comment]
Thanks Ben - I think I'm still looking for a sentence in the plugins db that gives examples of the metrics that it currently measures - like active users, new users etc etc - eg the text "the same metrics which are beaconed back to Moodle HQ when you register you site" is a bit generic and I'd like to see it covered it more detail within the plugins db.

**Comment by bwalkerl** [comment]
Thanks Dan - updated it again to be more specific:

> Metrics may be 'built in' ones such as the user activity metrics which are beaconed back to Moodle HQ when you register you site (online users, active users, new users, daily users), or they may be custom ones specific to your site.
