### ISSUE TITLE
invalid lang string (db approval blocker)

### ISSUE THREAD

**Issue by danmarsden** [catalyst/moodle-tool_cloudmetrics#163]
string concatentaion in the lang packs is not allowed - it causes problems for the Moodle translation tool

eg:
$string['test'] = "sometext"."somemoretext";
or
$string['test'] = "sometext".$string['someotheritem'];

each string must be contained within one set of quotes eg:
$string['test'] = "sometext somemoretext"; 

For example - this is not allowed:
https://github.com/catalyst/moodle-tool_cloudmetrics/blob/MOODLE_35_STABLE/collector/cloudwatch/lang/en/cltr_cloudwatch.php#L55

would be good to check if there are other cases within the subplugins and core langs.

**Comment by bwalkerl** [comment]
Resolved in https://github.com/catalyst/moodle-tool_cloudmetrics/pull/160
