### ISSUE TITLE
Settings being under plugins in the admin tree

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_cloudmetrics#17]

**Comment by jaypha** [comment]
Not sure what this is. Currently the settings is under 'Admin tools' on the plugins tab. Should it be somewhere else?

**Comment by brendanheywood** [comment]
Sorry this was the tool_excimer :(

**Comment by brendanheywood** [comment]
https://github.com/catalyst/moodle-tool_excimer/issues/177
