### ISSUE TITLE
When cleaning up old metrics in the database collector round it to the nearest day so we don't get half days of data left over

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_cloudmetrics#23]

**Comment by jaypha** [comment]
Would it be OK, to always move the cutoff further back in time to previous midnight, so that we always have at least the time given in the expiry value (i.e. if we have an expiry of 30 days, then we will always have at least 30 days of data.)?

It also make it easier to test.

**Comment by brendanheywood** [comment]
+1
