### ISSUE TITLE
Make the database collector generate some aggregate stats

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_cloudmetrics#40]
Maybe this is a new metric derived from another metric. Or maybe this is just some metadata that is generates for all metrics. The concrete case we want is for any minute or 5 minute metrics we also want to calculate the average and peak for each day.

Maybe this is a case of where the metric is built based on a new method that grind through old data and isn't dependent on cron calling it in the moment. In any case we'd want to show these metrics in their own right as their own graphs. We'd also want to group these metrics onto the same graph.

**Comment by jaypha** [comment]
This one also seems to have a lot of overlap with #74.
