### ISSUE TITLE
Database collector should be able to show multiple metrics on the same graph

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_cloudmetrics#41]
I'm thinking the chart page has a list down the left of all the metrics with checkboxes for each. You can toggle any combo on and off and bookmark that url.

The metrics should be listed with their schedule, generally you will want to mash together metrics which are mostly the same schedule or within a close range, eg 1 min + 15 minute, but not 1 min with 1 months.

**Comment by jaypha** [comment]
The Chart API is only capable of combining charts if they have the exact same input. It will be possible to combine them if they have the same schedule (and the same start and end points), but combining metrics of different schedules will only be possible if you strip away input times that are not common to all metrics.

**Comment by brendanheywood** [comment]
When we come back to this, I'd be more likely to want to interpolate the data to fill in the gaps rather than drop data. But this almost feels like a core deficiency in the chart api. If it gets too silly we can just use the chart libraries directly
