### ISSUE TITLE
Bug: inline editables need to have a default metric frequency

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_cloudmetrics#45]
This will die in install as well as when settings are unset:

php admin/cli/cfg.php --component=tool_cloudmetrics --name=onlineusers_frequency --unset

Coding error detected, it must be fixed by a programmer: Options for select element must contain an option for the specified value

http://moodle.local/admin/category.php?category=tool_cloudmetrics_reports

I think each metric should declare in code what its default frequency is rather than just relying on the admin settings like before

**Comment by jaypha** [comment]
What should the defaults be? I currently have

        activeusers: daily
        newusers: daily
        onlineusers: 5 min

**Comment by brendanheywood** [comment]
Yep that sounds great
