### ISSUE TITLE
Bug with cloudwatch skipping time periods

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_cloudmetrics#73]
There is a weird bug where only 2 out of 3 times end up in cloud watch so we get a discontinuous line graph

![image](https://user-images.githubusercontent.com/187449/167521714-e1ff3114-ee36-4782-baf2-2d6586697c03.png)

**Comment by jaypha** [comment]
This bug is happening because, by the time the task runs, the time has moved on sufficiently that it fails to match the frequency. Eg. For a five minute metric, at, say, 11:15, by the time the task starts running, it is now 11:16, at thus doesn't run any 5 minute metrics.
