### ISSUE TITLE
Clarify the exact semantics of is_ready

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_cloudmetrics#77]
ie does is_ready mean that the plugin simply has its dependencies met (eg cloudwatch has the aws sdk) or does it mean it is also configured and the connection it good?

Does it also assume that the plugin is enabled?

The key thing is whether a plugin can be disabled, but ready. Ie we know it is going to work, but we have turned it off.

This may end up mostly as a documentation task and not really change things

**Comment by jaypha** [comment]
My thinking is that is_ready() means that it is ready to receive data. So it must be enabled, properly configured, a good connection etc .. basically everything.

**Comment by brendanheywood** [comment]
is_ready for core cache stores means 'I have my php modules, and I am configured, and I can connect' so this all aligns well

So this should boil down to a few phpdoc updates
