### ISSUE TITLE
Clean up active users metrics

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_cloudmetrics#85]
https://github.com/catalyst/moodle-tool_cloudmetrics/tree/MOODLE_35_STABLE/metric/activeusers

vs

https://github.com/catalyst/moodle-tool_cloudmetrics/blob/MOODLE_35_STABLE/classes/metric/active_users_metric.php

I believe the former should be deleted

**Comment by jaypha** [comment]
Since metrics are no longer defined as sub-plugins, the 'metric' directory is redundant, and will be removed.
