### ISSUE TITLE
db collector chart: have an option to change the granularity of aggregation

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_cloudmetrics#98]
eg view a graph for 6 months worth of data, but change the resolution from daily to weekly

This means we average / min / max the data for each time slice. When we do this we will end up with 3 values not 1 and we can show them all on the graph together

**Comment by jaypha** [comment]
Is this a duplication of #74?

**Comment by brendanheywood** [comment]
yup
